### ISSUE TITLE
Permettre d'ajouter une option pour désactiver le scroll sur les cartes

### ISSUE THREAD

**Issue by thomas-benlevi** [Celyan-SAS/WordPress-GEOjson#3]
Soit par le biais d'un champs ACF, d'une page d'options dédiée au plugin ou bien depuis le shortcode.

**Comment by yannbug** [comment]
Le shortcode de carte intègre un nouvel attribut `map_options` (supporté uniquement pour les cartes au format leaflet qui est le type de cartes utilisé par défaut. Donc pas pour les Google Maps...)

Les options supportées sont décrites [ici dans la doc Leaflet](http://leafletjs.com/reference.html#map-dragging). Les options doivent être séparées par des virgules, sans espace, et on utilise un double-point (:) entre le nom de l'option et sa valeur.

Exemple pour désactiver le zoom avec la molette:
~~~
[su_wpgeojson_map file="https://dev94.citoyens.com/media/geojson/bureaux-primaire-droite-centre.geojson" height="450" popup_fields="num_bureau,adresse,salle,code_postal,ville" map_options="scrollWheelZoom:false"]
~~~

On peut voir [l'exemple ici](https://dev94.citoyens.com/test-carte-geojson)

**Comment by yannbug** [comment]
Plus qu'à faire pareil pour Google Maps...

**Comment by yannbug** [comment]
@thomas-benlevi maintenant ça marche pour Google Maps.

Exemple:

~~~
[su_wpgeojson_map map_type="google-maps" file="https://dev94.citoyens.com/media/geojson/bureaux-primaire-droite-centre.geojson" height="450" popup_fields="num_bureau,adresse,salle,code_postal,ville" map_options="scrollwheel:false"]
~~~

Les options disponibles pour l'attribut `map_options` pour les cartes Google Maps sont documentées ici: https://developers.google.com/maps/documentation/javascript/reference?hl=fr

(voir la partie "MapOptions object specification" / "Properties". 

PS : c'est bien un double-point (:) entre la propriété d'option et sa valeur.

Exemple avec `"scrollwheel:false"` visible [ici](https://dev94.citoyens.com/test-carte-google-maps)

**Comment by QuentinSalais** [comment]
Nickel merci beaucoup Yann ! :)
